--- 
abstract: CPAN Test Dummy for testing Module::Install::With
author: Adam Kennedy, C<< <cpan at ali.as> >>
distribution_type: module
generated_by: Module::Install version 0.65_0100
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: PITA-Test-Dummy-Perl5-MI
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.004
version: 0.65_01
