---
abstract: 'CPAN Test Dummy for testing Module::Install::With'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: PITA::Test::Dummy::Perl5::MI
name: PITA-Test-Dummy-Perl5-MI
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 0.77
