
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 0.61
name: PITA-Test-Dummy-Perl5-MI
author: Adam Kennedy, C<< <cpan at ali.as> >>
license: perl
requires: 
  perl: 5.004
abstract: CPAN Test Dummy for testing Module::Install::With
